using NUnit.Framework;
using Nybus.Configuration;
using Nybus.Utils;
using Ploeh.AutoFixture;

namespace Tests.Configuration
{
    [TestFixture]
    public class AutoGeneratedNameQueueStrategyTests
    {
        private IFixture fixture;

        [SetUp]
        public void Initialize()
        {
            fixture = new Fixture();
        }

        private AutoGeneratedNameQueueStrategy CreateSystemUnderTest()
        {
            return new AutoGeneratedNameQueueStrategy();
        }

        [Test]
        public void GetQueueName_is_unique_per_application()
        {
            var sut = CreateSystemUnderTest();

            var expected = Utilities.GetUniqueNameForApplication();

            var value = sut.GetQueueName();

            Assert.That(value, Is.EqualTo(expected));
        }
    }
}