trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: Cake@0
  inputs:
    script: 'build.cake'
    target: 'Full'
    verbosity: 'Normal'
  displayName: 'Execute Build script'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: 'outputs/tests/*.trx'
    mergeTestResults: true
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'outputs/'
    Contents: |
      *.nupkg
      *.snupkg
    TargetFolder: 'artifacts'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'artifacts'
    artifact: 'Packages'
