using Nybus.Configuration;

namespace Nybus.MassTransit
{
    public class MassTransitOptions
    {
        public int RetriesOnFaultyEvent { get; set; } = 5;

        public int RetriesOnFaultyCommand { get; set; } = 5;

        public IQueueStrategy CommandQueueStrategy { get; set; } = new AutoGeneratedNameQueueStrategy();

        public IQueueStrategy EventQueueStrategy { get; set; } = new TemporaryQueueStrategy();

        public IServiceBusFactory ServiceBusFactory { get; set; } = new DefaultServiceBusFactory();
    }
}